/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javaapplication7.frame_1_1;
/**
 *
 * @author KARTHIKEYAN.S.A.
 */
public class frame31 extends javax.swing.JFrame {

    /**
     * Creates new form frame31
     */
    public frame31() {
        initComponents();
        Toolkit tk=getToolkit();
        Dimension size=tk.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
      seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        session = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        mech = new javax.swing.JTextField();
        cse = new javax.swing.JTextField();
        exam = new javax.swing.JTextField();
        eee = new javax.swing.JTextField();
        eie = new javax.swing.JTextField();
        aero = new javax.swing.JTextField();
        ece = new javax.swing.JTextField();
        it = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNIVERSITY EXAMINATION");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATE");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("YEAR");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("SESSION");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("MONTH");

        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("ENTER DATE/MONTH/YEAR && SESSION");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("FORMAT(DD)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("FORMAT(MM)");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("FORMAT(YYYY)");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("FORMAT(FN/AN)");

        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        print.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("EXAM HALLS TO BE SELECTED");

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("<--BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examActionPerformed(evt);
            }
        });

        aero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("MAX.NO.OF HALLS AVAILABLE");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("28");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("6");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("6");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("4");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("5");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("6");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("6");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("6");

        submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("AERO BLOCK");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("EXAMCELL");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("IT BLOCK");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("ECE BLOCK");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("EIE BLOCK");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("MECH BLOCK");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("CSE BLOCK");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("EEE BLOCK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(month)
                                    .addComponent(year)
                                    .addComponent(session)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eee, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(it, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(exam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ece, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eie, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cse, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mech, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(back)
                        .addGap(87, 87, 87)
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addGap(114, 114, 114)
                        .addComponent(print)
                        .addGap(98, 98, 98)
                        .addComponent(exit)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back)
                            .addComponent(reset)
                            .addComponent(print)
                            .addComponent(exit)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(exam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(it, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel25))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        date.setText(null);
        month.setText(null);
        year.setText(null);
        session.setText(null);
        jTextArea2.setText(null);
        exam.setText(null);
        it.setText(null);
        ece.setText(null);
        mech.setText(null);
        eee.setText(null);
        eie.setText(null);
        aero.setText(null);
        cse.setText(null);
        submit.setEnabled(true);
        JOptionPane.showMessageDialog(null,"all data erased");
    }//GEN-LAST:event_resetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            jTextArea2.print();
        } catch (PrinterException ex1) {
            Logger.getLogger(frame31.class.getName()).log(Level.SEVERE, null, ex1);
        }

    }//GEN-LAST:event_printActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        systemexit();
        this.dispose();
        frame_1_1 f1=new frame_1_1();
        f1.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examActionPerformed

    private void aeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aeroActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        {  
	//day1data
        int date1=Integer.parseInt(date.getText());
        int month1=Integer.parseInt(month.getText());
        int year1=Integer.parseInt(year.getText());
        String s=session.getText();
        String c1=null;
        int d1=Integer.parseInt(exam.getText());
        int d2=Integer.parseInt(it.getText());
        int d3=Integer.parseInt(ece.getText());
        int d4=Integer.parseInt(aero.getText());
        int d5=Integer.parseInt((eie.getText()));
        int d6=Integer.parseInt(eee.getText());
        int d7=Integer.parseInt(cse.getText());
        int d8=Integer.parseInt(mech.getText());
        int m=1,e1=0;
        frame31 f3=new frame31();
        ArrayList<String> tg=new ArrayList<String>();
        ArrayList<String> tg3=new ArrayList<String>();
        ArrayList<String> tg1=new ArrayList<String>();
        ArrayList<String> tg2=new ArrayList<String>();
        ArrayList<String> tg4=new ArrayList<String>();
        ArrayList<String> tg5=new ArrayList<String>();
        ArrayList<String> tg6=new ArrayList<String>();
        ArrayList<String> tg7=new ArrayList<String>();
        tg7.add("Dr.BALAPRIYA.R(IT)(AP)");
	tg7.add("Mrs.UMAMAGESWARI.R.M(IT)(AP)");
	tg7.add("Mrs.SUNITHA. R(IT)(AP)");
	tg7.add("Ms.KEERTHIKA .A(IT)(AP)");
	tg7.add("Ms.NIRMALA .N(IT)(AP)");
	tg7.add("Mr. VENKATESH .A(IT)(AP)");
	tg7.add("Mrs.NITHISHA.J(IT)(AP)");
	tg7.add("Mrs.FREEDA(S&H)(P)");
	tg7.add("Mr.SUBASH CHANDAR(CSE)(AP)");
	tg7.add("Mrs. MADHURIKKHA(CSE)(AP)");
	tg7.add("Mrs.ANITHA GNANA SELVI.J(CSE)(AP)");
	tg7.add("Mrs. MALINI.P(CSE)(AP)");
	tg7.add("Mrs.BEULA DAVID(CSE)(AP)");
	tg7.add("Mrs.DEEBALAKSHMI(CSE)(AP)");
	tg7.add("Dr.MONICA CHANA MALAR.I(CSE)(AP)");
	tg7.add("Mr.PRATHAP.S(CSE)(AP)");
	tg7.add("Mr.VENKATESH.S(CSE)(AP)");
	tg7.add("Dr.JOSPIN JEYA .J(CSE)(AP)");
	tg7.add("Mrs.VIDHYA.A(CSE)(AP)");
	tg7.add("Mr.GOWTHAMAN .M(CSE)(AP)");
	tg7.add("Ms.T.KALPANA PRIYADHARSHINI(CSE)(AP)");
	tg7.add("Ms.GOMATHY .M(CSE)(AP)");
	tg7.add("Dr.J.WILSON SAHAYARAJ(S&H)(P)");
	tg7.add("Ms.MADHUMATHI .M(CSE)(AP)");
	tg7.add("Ms.PRIYADHARSHINI.S(CSE)(AP)");
        tg6.add("Mr.DINAKARAN.M(MECH)(AP)");
	tg6.add("Dr.TAMILSELVI.P(CSE)(P)");
	tg6.add("Dr.JAGADEESAN(MECH)(AP)");
	tg6.add("Mr.MELVIN VICTOR(MECH)(AP)");
	tg6.add("Mr.MUTHUKAMATCHI(MECH)(AP)");
	tg6.add("Mr.PREMKUMAR.N(MECH)(AP)");
	tg6.add("Mr.JEEVA(MECH)(AP)");
	tg6.add("Dr. VISUMATHI J(CSE)(P)");
	tg6.add("Mr.BALAGURU.R(MECH)(AP)");
	tg6.add("Mr.RAJKUMAR .D(MECH)(AP)");
	tg6.add("Mr.RAMADOSS .J(MECH)(AP)");
	tg6.add("Mr.AKHIL .T(MECH)(AP)");
	tg6.add("Mr.JOEL(MECH)(AP)");
	tg6.add("Ms.JAYALAKSHMI DEVI.V(EIE)(P)");
	tg6.add("Mr. GLADWIN.A(IT)(AP)");
	tg6.add("Mr. FENIL.E(IT)(AP)");
	tg6.add("Mrs.GNANA JESLIN(IT)(AP)");
	tg6.add("Mr. P.VAISAGAN(IT)(AP)");
	tg6.add("Mr.AYYAPPAN.B(IT)(AP)");
	tg6.add("Mr. SARAVANAN.T(IT)(AP)");
	tg6.add("Mr. VIMAL(IT)(AP)");
	tg6.add("Mrs. SUMATHY.G(IT)(AP)");
	tg6.add("Mrs. GODFRIN(IT)(AP)");
	tg6.add("Mrs.TITUS.S(IT)(AP)");
	tg6.add("Dr.VERONICA SHALINI.J(BIO)(p)");
	tg6.add("Dr.THILAGAVATHY. S.R(IT)(AP)");
        tg5.add("Dr.SIVASELVAN.K(MECH)(AP)");
	tg5.add("Mr.ARUN KUMAR .T(MECH)(AP)");
	tg5.add("Mr. BALA KALANITHI(MECH)(AP)");
	tg5.add("Mr.JEGANDHAS P(MECH)(AP)");
	tg5.add("Dr. JESU JAYARIN P(CSE)(P)");
	tg5.add("Mr.BROSTER M(MECH)(AP)");
	tg5.add("Mr. K. ARUL(MECH)(AP)");
	tg5.add("Mr.DILIP SINGH(MECH)(AP)");
	tg5.add("Mr.AYYANDURAI M(MECH)(AP)");
	tg5.add("Mr.VELMURUGAN.G(MECH)(AP)");
	tg5.add("Mrs.GIRIJA M.S.(CSE)(P)");
	tg5.add("Mr.V. MURUGAMANI(MECH)(AP)");
	tg5.add("Mr.GOPAL.K(MECH)(AP)");
	tg5.add("Mr. DAMODARAN.D(MECH)(AP)");
	tg5.add("Mr. CHELLAPANDI.P(MECH)(AP)");
	tg5.add("Mr.G. DEVARAJ(MECH)(AP)");
	tg5.add("Mrs.DHANALAKSHMI(CSE)(P)");
	tg5.add("Mr. JAGATHEESAN.K(MECH)(AP)");
	tg5.add("Dr.MADHESH.D(MECH)(AP)");
	tg5.add("Mr.DHINAKARAN.S(MECH)(AP)");
	tg5.add("Mr.RAJESH KUMAR.N(MECH)(AP)");
        tg4.add("Dr.CHITRA(EEE)(AP)");
	tg4.add("Mrs. RAJA RAJESWARI(EEE)(AP)");
	tg4.add("Mr. WILSON .P(EEE)(AP)");
	tg4.add("Mrs. BHARATHI.K(EEE)(AP)");
	tg4.add("Mr. ARUN KUMARAN .B(EEE)(AP)");
	tg4.add("Mr. RAMARAJAN.S(EEE)(AP)");
	tg4.add("Mr. PRAVEEN.M(EEE)(AP)");
	tg4.add("Mrs. GNANA SOUNDARI.A(IT)(P)");
	tg4.add("Mr.ANTHONY RAJ(EEE)(AP)");
	tg4.add("Mr.KALANITHI.C(EEE)(AP)");
	tg4.add("Ms.CHITRA .S(EEE)(AP)");
	tg2.add("Mr.MANOJPRABU.PR(EEE)(AP)");
	tg2.add("Ms.BAKIYALAKSHMI(EEE)(AP)");
	tg2.add("Mr.JOHN FREDERICK.J(EEE)(AP)");
	tg2.add("Ms. THARINI(EEE)(AP)");
	tg2.add("Mrs.AMUTHA(civil)(p)");
        tg2.add("Dr. SUMATHY RAJKUMAR .M(S&H)(P)");
	tg2.add("Mr.THANIKAIVEL MURUGAN (AERO)(AP)");
	tg2.add("Mr.KANNAN.(AERO)(AP)");
	tg2.add("Mr.HASTON AMIT KUMAR(AERO)(AP)");
        tg1.add("Ms.VIJAYALAKSHMI.V(EIE)(AP)");
	tg1.add("Mr.ARUN RAJESH(EIE)(AP)");
	tg1.add("Dr.SRIDHAR.S(BIO)(AP)");
	tg1.add("Mrs.INBAVALLI.M(BIO)(AP)");
	tg1.add("Mr.JEYAMANIKANDAN(BIO)(AP)");
	tg1.add("Dr.THIRIPURAM.A(BIO)(AP)");
	tg1.add("Mr.SORNA KUMAR .R.S.A(BIO)(AP)");
	tg1.add("Mr.KARTHIKEYAN.N(EEE)(p)");
 	tg1.add("Mr. MANIKANDAN S(AERO)(AP)");
	tg1.add("Mr.THIYAGU .R(AERO)(AP)");
	tg1.add("Mrs.GOMATHI SANKAR .G(BIO)(AP)");
	tg1.add("Mr.GOPI ANAND(BIO)(AP)");
	tg1.add("Mrs.SREELEKHALAKSHMI.D(BIO)(AP)");
	tg1.add("Ms.SUBASHINI .V(S&H)(AP)");
	tg1.add("Mrs.LAKSHMI .V(S&H)(AP)");
        tg1.add("Mrs.NANAMMAL.V(ECE)(AP)");
	tg1.add("Mrs.SHOBANA.R(ECE)(AP)");
	tg1.add("Mr.RAJARAJAN.R(ECE)(AP)");
	tg1.add("Mrs.K.SUBASHINI(ECE)(AP)");
	tg1.add("Ms.MADONA .B SAHAAI(ECE)(AP)");
	tg1.add("Ms.SANTHIYA .A(ECE)(AP)");
	tg1.add("Ms.PITCHAIKANI .A(ECE)(AP)");
	tg1.add("Mrs.SATHYAKALA.A.K(S&H)(AP)");
	tg1.add("Mr.STEEPHENRAJ.A(S&H)(AP)");
	tg1.add("Mr.PREMANAND .G(S&H)(AP)"); 
        tg.add("Mr. SATISH KUMAR.S(EEE)(P)");
	tg.add("Mr.THANIKAIVEL MURUGAN (AERO)(AP)");
	tg.add("Mr.KANNAN.(AERO)(AP)");
	tg.add("Mr.HASTON AMIT KUMAR(AERO)(AP)");
	tg.add("Mr. NELSON. H(AERO)(AP)");
	tg.add("Ms.USHA BHARATHI(AERO)(AP)");
	tg.add("Ms.VISHNUPRIYA .T(ECE)(AP)");
	tg.add("Mr.RANJITHKUMAR.J(ECE)(AP)");
	tg.add("Ms.ANGELINE PRINCY .V(ECE)(AP)");
	tg.add("Mrs. SHANMUGA KANI.P(EIE)(AP)");
	tg.add("Mrs. SASIKALA.R(EIE)(AP)");
	tg.add("Mr. VIVEK KRISHNA.R(EIE)(AP)");
	tg.add("Mr.JEYARAMAN(EIE)(AP)");
	tg.add("Mrs. K.REVATHI(EIE)(AP)");
	tg.add("Mr.G.KALAISELVAN(EIE)(AP)");
	tg.add("Mrs.DAISY RANI(EIE)(AP)");
	tg.add("Mrs.NITHYA.J(EIE)(AP)");
	tg.add("Ms.DEVI SUDHA(EIE)(AP)");
	tg.add("Mrs.SIVAGAMI.P(EIE)(AP)");
	tg.add("Dr.S BENJAMIN ARUL(EIE)(AP)");
	tg.add("Mrs. DHIVYA PRIYA B(EIE)(AP)");
	tg.add("Mr.REGAN MARIA SUNDARRAJ.F(EIE)(AP)");
	tg.add("Ms.MICHEAL PRIYANKA .M(EIE)(AP)");
	tg.add("Ms.ATCHAYA(EIE)(AP)");
	tg.add("Ms.HEMALATHA.G(CSE)(AP)");
	tg.add("Mrs.MALATHI.P(CSE)(AP)");
	tg.add("Ms.PRIYANKA PRAMILA(CSE)(AP)");
	tg.add("Mrs.ANITHA.C(ECE)(AP)");
	tg.add("Mr.RAMESH.S(ECE)(AP)");
	tg.add("Mr.BALACHANAN.G(ECE)(AP)");
	tg.add("Dr. SUMATHY RAJKUMAR .M(S&H)(P)");
	tg.add("Mr.M.SUMAN(ECE)(AP)");
	tg.add("Mrs. BHAVANI.R(ECE)(AP)");
	tg.add("Mr.S.RANJITH(ECE)(AP)");
	tg.add("Mr.G.C.JAGAN(ECE)(AP)");
	tg.add("Mr. ARUN VIJAYA KUMAR.B(ECE)(AP)");
	tg.add("Ms.CHENTHIL.T.R(ECE)(AP)");
        tg3.add("Mr. PURUSHOTHAMAN.M(MECH)(P)");
        tg3.add("Mr.MOHAN KUMAR S(Civil)(AP)");
        tg3.add("Ms.PARAMESWARI M(Civil)(AP)");
        tg3.add("Ms.ARUNTATHI(Civil)(AP)");
        tg3.add("Ms. ALPHONSA ANTONY(Civil)(AP)");
        tg3.add("Ms. SANTHIYA .C(Civil)(AP)");
        tg3.add("Ms. POOJARAMDAS(Civil)(AP)");
        tg3.add("Ms.SINDHUJA  .T(Civil)(AP)");
        tg3.add("Ms. BEAULA JASMINE .R(Civil)(AP)");
        tg3.add("Dr.P.MOHANKUMAR(IT)(P)");
        tg3.add("Mr. ARUN SRINIVAS.T(EEE)(AP)");
        tg3.add("Mrs. MANJULA.H.S(EEE)(AP)");
        tg3.add("Mrs. PRAVINA.P(EEE)(AP)");
        tg3.add("Mr. SAKTHI.S(EEE)(AP)");
        tg3.add("Mrs. KAVITHA KUMARI .K.S(EEE)(AP)");
        tg3.add("Mr. BALABHARATHI.B(EEE)(AP)");
        tg3.add("Dr. UDAYALAKSHMI .K(EEE)(AP)");
        tg3.add("Mrs. PACKIALATHA.A(IT)(P)");
        //exam
        e1=dayofweek(date1,month1,year1);
       if(e1==1)
    {/*c="sunday";*/d1=d1+1;c1="monday";}
    else if(e1==2)
    {c1="monday";}
    else if (e1==3)
    {c1="tuesday";
    }else if (e1==4)
    {c1="wednesday";
    }else if (e1==5)
    {c1="thursday";
    }else if (e1==6)
    {c1="friday";
    }else
    {c1="saturday";}
        
        jTextArea2.append("\t\t\t                  JEPPIAAR ENGINEERING COLLEGE\n\t\t\tJeppiaar Nagar,Old Mamallapuram Road,Chennai-119.\n\t\t\tSEATING ARRANGEMENT FOR UG/PG(REGULAR/ARREAR)\n");
        jTextArea2.append("\tcentre code and Name:  3108 , Jeppiaar Engineering College ");
        jTextArea2.append("\t\t\tDATE:"+date1+"/"+month1+"/"+year1+"\n\t\t\t\t\t\t\tSESSION:"+s+"\n");
        jTextArea2.append("\t\t\t\t\t\t\tDAY: "+c1+"\n");
        jTextArea2.append("=================================================================================================================================\n");
        if(d1==0)
        {
        jTextArea2.append("examcell no halls selected\n");
        }
        else{
        jTextArea2.append("EXAMCELL BLOCK\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d1;i++)
        {
            if(i==1){jTextArea2.append("HALL I-A"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("HALL I-B"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("HALL I-C"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("HALL I-D"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append( "HALL I-E"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append( "HALL I-F"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");} 
            else if(i==7){jTextArea2.append( "HALL I-G"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==8){jTextArea2.append( "HALL I-H"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==9){jTextArea2.append( "HALL I-I"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==10){jTextArea2.append( "HALL II-L"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==11){jTextArea2.append(  "HALL II-M"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");} 
            else if(i==12){jTextArea2.append("HALL II-N"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");
            }else if(i==13){jTextArea2.append("HALL II-O"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==14){jTextArea2.append( "HALL III-Q"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==15){jTextArea2.append( "HALL III-R"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==16){jTextArea2.append(  "HALL III-S"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==17){jTextArea2.append( "HALL III-T"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==18){jTextArea2.append("HALL III-U"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==19){jTextArea2.append("HALL III-V"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==20){jTextArea2.append("HALL III-d"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==21){jTextArea2.append( "HALL III-W"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==22){jTextArea2.append( "HALL IV-X"+"\texamcell/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==23){jTextArea2.append("HALL IV-Y"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==24){jTextArea2.append("HALL IV-Z"+"\texamcell/second floor"+"\t"+""+"\t"+""+ "\n");}
            else if(i==25){jTextArea2.append("HALL IV-a"+"\texamcell/second floor"+"\t"+f3.getRandomElementec(tg,m)+"\t"+""+"\n");}
            else if(i==26){jTextArea2.append("HALL IV-b"+"\texamcell/second floor"+"\t"+""+"\t"+"" );break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}
        }
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d2==0)
        {
        jTextArea2.append("IT no halls selected\n");
        }
        else
        {
        jTextArea2.append("IT block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d2;i++)
        {
            if(i==1){jTextArea2.append( "HALL 12"+"\tIT block/ground floor"+"\t"+f3.getRandomElementit(tg1,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("HALL 13"+"\tIT block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append( "HALL 14"+"\tIT block/ground floor"+"\t"+f3.getRandomElementit(tg1,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("HALL 15"+"\tIT block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append("HALL 16"+"\tIT block/ground floor"+"\t"+f3.getRandomElementit(tg1,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append( "HALL 17"+"\tIT block/ground floor"+"\t"+""+"\t"+"");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d3==0)
        {
        jTextArea2.append("ece no halls selected\n");
        }
        else
        {
        jTextArea2.append("ECE block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d3;i++)
        {
            if(i==1){jTextArea2.append( "ECE G3"+"\tECE block/ground floor"+"\t"+f3.getRandomElementece(tg2,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("ECE G4"+"\tECE block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("ECE G5"+"\tECE block/ground floor"+"\t"+f3.getRandomElementece(tg2,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("ECE G6"+"\tECE block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append("ECE G7"+"\tECE block/ground floor"+"\t"+f3.getRandomElementece(tg2,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append("ECE G8"+"\tECE block/ground floor"+"\t"+""+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d4==0)
        {
        jTextArea2.append("aero no halls selected\n");
        }
        else
        {
        jTextArea2.append("AERO block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d4;i++)
        {
            if(i==1){jTextArea2.append("AERO S1"+"\tAERO block/second  floor"+"\t"+f3.getRandomElementaero(tg3,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("AERO S2"+"\tAERO block/second  floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("AERO S3"+"\tAERO block/second  floor"+"\t"+f3.getRandomElementaero(tg3,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("AERO S4"+"\tAERO block/second  floor"+"\t"+""+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d5==0)
        {
        jTextArea2.append("eie no halls selected\n");
        }
        else
        {
        jTextArea2.append("EIE block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d5;i++)
        {
            if(i==1){jTextArea2.append("E&I G1"+"\tEIE block/ground floor"+"\t"+f3.getRandomElementeie(tg4,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("E&I G2"+"\tEIE block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append( "E&I G3"+"\tEIE block/ground floor"+"\t"+f3.getRandomElementeie(tg4,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("E&I G4"+"\tEIE block/ground floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append( "E&I G7"+"\tEIE block/ground floor"+"\t"+f3.getRandomElementeie(tg4,m)+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d6==0)
        {
        jTextArea2.append("eee no halls selected\n");
        }
        else
        {
        jTextArea2.append("EEE block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d6;i++)
        {
            if(i==1){jTextArea2.append("EEE F1"+"\tEEE block/first floor"+"\t"+f3.getRandomElementeee(tg5,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("EEE F2"+"\tEEE block/first floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("EEE F3"+"\tEEE block/first floor"+"\t"+f3.getRandomElementeee(tg5,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("EEE F5"+"\tEEE block/first floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append("EEE F6"+"\tEEE block/first floor"+"\t"+f3.getRandomElementeee(tg5,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append("EEE F7"+"\tEEE block/first floor"+"\t"+""+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d7==0)
        {
        jTextArea2.append("cse no halls selected\n");
        }
        else
        {
        jTextArea2.append("CSE block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d7;i++)
        {
            if(i==1){jTextArea2.append( "CSE G1"+"\tCSE block/groung floor"+"\t"+f3.getRandomElementcse(tg6,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("CSE F2"+"\tCSE block/groung floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("CSE F3"+"\tCSE block/groung floor"+"\t"+f3.getRandomElementcse(tg6,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("CSE F5"+"\tCSE block/groung floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append("CSE F6"+"\tCSE block/groung floor"+"\t"+f3.getRandomElementcse(tg6,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append("CSE F7"+"\tCSE block/groung floor"+"\t"+""+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
        if(d8==0)
        {
        jTextArea2.append("mech no halls selected\n");
        }
        else
        {
        jTextArea2.append("MECH block\n"+"HALL NO"+"\tBLOCK/FLOOR"+"\tFACULTY NAME"+"\tPHONE NUMBER\n");
        for(int i=1;i<=d8;i++)
        {
            if(i==1){jTextArea2.append("MECH S1"+"\tMECH block/second floor"+"\t"+f3.getRandomElementmech(tg7,m)+"\t"+""+"\n");}
            else if(i==2){jTextArea2.append("MECH S2"+"\tMECH block/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==3){jTextArea2.append("MECH S3"+"\tMECH block/second floor"+"\t"+f3.getRandomElementmech(tg7,m)+"\t"+""+"\n");}
            else if(i==4){jTextArea2.append("MECH S5"+"\tMECH block/second floor"+"\t"+""+"\t"+""+"\n");}
            else if(i==5){jTextArea2.append("MECH S6"+"\tMECH block/second floor"+"\t"+f3.getRandomElementmech(tg7,m)+"\t"+""+"\n");}
            else if(i==6){jTextArea2.append("MECH S7"+"\tMECH block/second floor"+"\t"+""+"\t"+""+"\n");break;}
            else{JOptionPane.showMessageDialog(null,"error hall,click reset");}}
        }
        jTextArea2.append("=================================================================================================================================\n");
 submit.setEnabled(false);}
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame31().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aero;
    private javax.swing.JButton back;
    private javax.swing.JTextField cse;
    private javax.swing.JTextField date;
    private javax.swing.JTextField ece;
    private javax.swing.JTextField eee;
    private javax.swing.JTextField eie;
    private javax.swing.JTextField exam;
    private javax.swing.JButton exit;
    private javax.swing.JTextField it;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField mech;
    private javax.swing.JTextField month;
    private javax.swing.JButton print;
    private javax.swing.JButton reset;
    private javax.swing.JTextField session;
    private javax.swing.JButton submit;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
private void systemexit()
{
    WindowEvent winCloseing=new WindowEvent(this,WindowEvent.WINDOW_CLOSED);
}
public ArrayList<String> getRandomElementaero(ArrayList<String> tg3, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg3.size());	
	nlist.add(tg3.get(ri));
	tg3.remove(ri);
	}
	return nlist;
} 
 public ArrayList<String> getRandomElementec(ArrayList<String> tg, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg.size());	
	nlist.add(tg.get(ri));
	tg.remove(ri);
	}
	return nlist;
}
public ArrayList<String> getRandomElementit(ArrayList<String> tg1, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg1.size());	
	nlist.add(tg1.get(ri));
	tg1.remove(ri);
	}
	return nlist;
} 
public ArrayList<String> getRandomElementece(ArrayList<String> tg2, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg2.size());	
	nlist.add(tg2.get(ri));
	tg2.remove(ri);
	}
	return nlist;
} 
public ArrayList<String> getRandomElementeie(ArrayList<String> tg4, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg4.size());	
	nlist.add(tg4.get(ri));
	tg4.remove(ri);
	}
	return nlist;
}
public ArrayList<String> getRandomElementeee(ArrayList<String> tg5, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg5.size());	
	nlist.add(tg5.get(ri));
	tg5.remove(ri);
	}
	return nlist;
} 
public ArrayList<String> getRandomElementcse(ArrayList<String> tg6, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg6.size());	
	nlist.add(tg6.get(ri));
	tg6.remove(ri);
	}
	return nlist;
} 
public ArrayList<String> getRandomElementmech(ArrayList<String> tg7, int totalItems) 
{
	Random r=new Random();
	ArrayList <String> nlist=new ArrayList<String>(); 
	for(int i=0;i<totalItems;i++){
	int ri=r.nextInt(tg7.size());	
	nlist.add(tg7.get(ri));
	tg7.remove(ri);
	}
	return nlist;
} 
 public int dayofweek(int d1, int m1, int y1) {
		int t[]= {0,3,2,5,0,3,5,1,4,6,2,4};
		y1-=(m1<3)?1:0;
		return( y1+ y1/4- y1/100 + y1/100 + t[m1-1] + d1 ) % 7;
}

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("staff-allocation-human-resource-labor-128.png")));
    }

    
}
